// Array of continents with their codes and names
export const ALL_CONTINENTS = [
  { code: "", name: "All Continents" },
  { code: "EU", name: "Europe" },
  { code: "AS", name: "Asia" },
  { code: "AF", name: "Africa" },
  { code: "NA", name: "North America" },
  { code: "SA", name: "South America" },
  { code: "OC", name: "Oceania" },
  { code: "AN", name: "Antarctica" },
];

// Array of currencies with their codes and names
export const ALL_CURRENCIES = [
  { code: "", name: "All Currencies" },
  { code: "USD", name: "USD" },
  { code: "EUR", name: "EUR" },
  { code: "INR", name: "INR" },
  { code: "AED", name: "AED" },
  { code: "AFN", name: "AFN" },
  { code: "XCD", name: "XCD" },
  { code: "ALL", name: "ALL" },
  { code: "AMD", name: "AMD" },
  { code: "AOA", name: "AOA" },
  { code: "ARS", name: "ARS" },
  { code: "AUD", name: "AUD" },
  { code: "AWG", name: "AWG" },
  { code: "AZN", name: "AZN" },
  { code: "BAM", name: "BAM" },
  { code: "BBD", name: "BBD" },
  { code: "BDT", name: "BDT" },
  { code: "XOF", name: "XOF" },
  { code: "BGN", name: "BGN" },
  { code: "BHD", name: "BHD" },
  { code: "BIF", name: "BIF" },
  { code: "BMD", name: "BMD" },
  { code: "BND", name: "BND" },
  { code: "BOB", name: "BOB" },
  { code: "BRL", name: "BRL" },
  { code: "BSD", name: "BSD" },
  { code: "BTN", name: "BTN" },
  { code: "NOK", name: "NOK" },
  { code: "BWP", name: "BWP" },
  { code: "BYN", name: "BYN" },
  { code: "BZD", name: "BZD" },
  { code: "CAD", name: "CAD" },
  { code: "CDF", name: "CDF" },
  { code: "CHF", name: "CHF" },
  { code: "CNY", name: "CNY" },
  { code: "COP", name: "COP" },
  { code: "CRC", name: "CRC" },
  { code: "CUC", name: "CUC" },
  { code: "CUP", name: "CUP" },
  { code: "CVE", name: "CVE" },
  { code: "CZK", name: "CZK" },
  { code: "DJF", name: "DJF" },
  { code: "DKK", name: "DKK" },
  { code: "DOP", name: "DOP" },
  { code: "DZD", name: "DZD" },
  { code: "EGP", name: "EGP" },
  { code: "MAD", name: "MAD" },
  { code: "ERN", name: "ERN" },
  { code: "ETB", name: "ETB" },
  { code: "FJD", name: "FJD" },
  { code: "FKP", name: "FKP" },
  { code: "GEL", name: "GEL" },
  { code: "GHS", name: "GHS" },
  { code: "GIP", name: "GIP" },
  { code: "GMD", name: "GMD" },
  { code: "GNF", name: "GNF" },
  { code: "GTQ", name: "GTQ" },
  { code: "GYD", name: "GYD" },
  { code: "HKD", name: "HKD" },
  { code: "HNL", name: "HNL" },
  { code: "HRK", name: "HRK" },
  { code: "HTG", name: "HTG" },
  { code: "HUF", name: "HUF" },
  { code: "IDR", name: "IDR" },
  { code: "ILS", name: "ILS" },
  { code: "IQD", name: "IQD" },
  { code: "IRR", name: "IRR" },
  { code: "ISK", name: "ISK" },
  { code: "JMD", name: "JMD" },
  { code: "JOD", name: "JOD" },
  { code: "JPY", name: "JPY" },
  { code: "KES", name: "KES" },
];
